"""Initial migration.

Revision ID: 95f341e069fa
Revises: 
Create Date: 2024-07-24 04:08:16.108813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f341e069fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('packet_length', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(length=100), nullable=False),
    sa.Column('dst_ip', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.Integer(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('protocol_type', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('src_bytes', sa.Integer(), nullable=False),
    sa.Column('dst_bytes', sa.Integer(), nullable=False),
    sa.Column('land', sa.Integer(), nullable=False),
    sa.Column('wrong_fragment', sa.Integer(), nullable=False),
    sa.Column('urgent', sa.Integer(), nullable=False),
    sa.Column('hot', sa.Integer(), nullable=False),
    sa.Column('num_failed_logins', sa.Integer(), nullable=False),
    sa.Column('logged_in', sa.Integer(), nullable=False),
    sa.Column('num_compromised', sa.Integer(), nullable=False),
    sa.Column('root_shell', sa.Integer(), nullable=False),
    sa.Column('su_attempted', sa.Integer(), nullable=False),
    sa.Column('num_root', sa.Integer(), nullable=False),
    sa.Column('num_file_creations', sa.Integer(), nullable=False),
    sa.Column('num_shells', sa.Integer(), nullable=False),
    sa.Column('num_access_files', sa.Integer(), nullable=False),
    sa.Column('num_outbound_cmds', sa.Integer(), nullable=False),
    sa.Column('is_host_login', sa.Integer(), nullable=False),
    sa.Column('is_guest_login', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('srv_count', sa.Integer(), nullable=False),
    sa.Column('serror_rate', sa.Float(), nullable=False),
    sa.Column('srv_serror_rate', sa.Float(), nullable=False),
    sa.Column('rerror_rate', sa.Float(), nullable=False),
    sa.Column('srv_rerror_rate', sa.Float(), nullable=False),
    sa.Column('same_srv_rate', sa.Float(), nullable=False),
    sa.Column('diff_srv_rate', sa.Float(), nullable=False),
    sa.Column('srv_diff_host_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_count', sa.Integer(), nullable=False),
    sa.Column('dst_host_srv_count', sa.Integer(), nullable=False),
    sa.Column('dst_host_same_srv_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_diff_srv_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_same_src_port_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_srv_diff_host_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_serror_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_srv_serror_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_rerror_rate', sa.Float(), nullable=False),
    sa.Column('dst_host_srv_rerror_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('secret_key', sa.String(length=16), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.drop_table('device')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('login_attempt')
    op.drop_table('alert')
    op.drop_table('access_log')
    # ### end Alembic commands ###
